### ISSUE TITLE
What is the Adjacent Rejection rule for chest CT scans(LIDC)? What is the major differences between lnd and lnd-tl?

### ISSUE THREAD

**Issue by guyucowboy** [jmendozais/lung-nodule-detection#1]
Hi, jmendozais:
    Thanks for sharing your codes.  I have some questions to ask you.
    1. What is the Adjacent Rejection rule for chest CT scans(LIDC)? I see that the  Adjacent Rejection rule for CR images (JSRT) was set with radial neighborhood of 22 mm. How about chest CT scans? Are they same?
    2. What is the major differences between lnd.py and lnd-tl.py? Which script should be executed when LIDC datasets are used to detect lung nodules?
    Thanks for your helps!
Best regards
Gu Yu

**Comment by jmendozais** [comment]
Hi @guyucowboy, sorry for the delay,
1. The adjacent rejection rule is the same for CR images in JSRT and LIDC-IDRI. This work only considers CR images on LIDC-IDRI, but not CT scans. 
2. lnd.tl.py was created to test off-the-shelf models on CR images as well. LIDC-IDRI is used by default on training with -model-selection, and on test with -model evaluation flags.

**Comment by guyucowboy** [comment]
Hi, jmendozais:
Thanks for your reply. I may consult you when I have some questions. Thanks for your help! -:)
Best regards
Gu Yu

**Comment by jmendozais** [comment]
you're welcome :)!
